### ISSUE TITLE
[BUG] Node ODBC will not compile from version 18.20 onwards, and several other minor version increments

### ISSUE THREAD

**Issue by yamadapc** [IBM/node-odbc#396]
Caused by https://github.com/nodejs/node/pull/50060 

I believe breaks from version `18.20.0` onwards, and all versions that include that change.

To fix this, `odbc` must

* Define `NODE_API_EXPERIMENTAL_NOGC_ENV_OPT_OUT`

**Comment by kadler** [comment]
Thanks for the detailed report. This was fixed in #381 and we'll be releasing a new version soon.

**Comment by kadler** [comment]
We've released version 2.4.9 which includes the NAPI_EXPERIMENTAL fix: https://www.npmjs.com/package/odbc/v/2.4.9
